# pull a basic set of aspects, unit groups, and units of measure

prefix gist:  <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix gistd: <https://w3id.org/semanticarts/ns/data/gist/>
prefix gistx: <https://w3id.org/semanticarts/ns/data/gist/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

construct {
  
  ?unit   gist:isMemberOf  ?unitGroup .  
  ?aspect gist:hasUnitGroup ?unitGroup  .  
  ?aspect gist:isCategorizedBy ?discipline .
  
  ?unit       ?unitPredicate       ?unitObject .
  ?unitGroup  ?unitGroupPredicate  ?unitGroupObject .
  ?aspect     ?aspectPredicate     ?aspectObject .
  ?discipline ?disciplinePredicate ?disciplineObject .
 }

where {
  
  values (?discipline ?aspect ?unit)  {

#     (gistd:_Discipline_acoustics  gistd:_Aspect_frequency  gistd:_UnitOfMeasure_gigahertz)
#     (gistd:_Discipline_acoustics  gistd:_Aspect_frequency  gistd:_UnitOfMeasure_hertz)
#     (gistd:_Discipline_acoustics  gistd:_Aspect_sound_power_level  gistd:_UnitOfMeasure_decibel)
    
 #    (gistd:_Discipline_atomic_physics  gistd:_Aspect_atomic_charge  gistd:_UnitOfMeasure_elementary_charge)
 #    (gistd:_Discipline_atomic_physics  gistd:_Aspect_atomic_charge  gistd:_UnitOfMeasure_planck_charge)
 #    (gistd:_Discipline_atomic_physics  gistd:_Aspect_atomic_mass    gistd:_UnitOfMeasure_atomic_mass_unit)    

#     (gistd:_Discipline_biology  gistd:_Aspect_blood_pressure  gistd:_UnitOfMeasure_millimeter_of_mercury)
     (gistd:_Discipline_biology  gistd:_Aspect_genetic_strand_length  gistd:_UnitOfMeasure_gigabase_pair)
#     (gistd:_Discipline_biology  gistd:_Aspect_heart_rate  gistd:_UnitOfMeasure_count_per_minute)
     (gistd:_Discipline_biology  gistd:_Aspect_rate_of_morbidity  gistd:_UnitOfMeasure_cases_per_1000_individuals_per_year)
     (gistd:_Discipline_biology  gistd:_Aspect_rate_of_mortality  gistd:_UnitOfMeasure_deaths_per_million_individuals_per_year)
#     (gistd:_Discipline_biology  gistd:_Aspect_respiratory_rate  gistd:_UnitOfMeasure_count_per_minute)

     (gistd:_Discipline_biometrics  gistd:_Aspect_blood_pressure  gistd:_UnitOfMeasure_millimeter_of_mercury)
     (gistd:_Discipline_biometrics  gistd:_Aspect_heart_rate  gistd:_UnitOfMeasure_count_per_minute)
     (gistd:_Discipline_biometrics  gistd:_Aspect_respiratory_rate  gistd:_UnitOfMeasure_count_per_minute)

#     (gistd:_Discipline_chemistry  gistd:_Aspect_amount_of_substance  gistd:_UnitOfMeasure_international_unit)
#     (gistd:_Discipline_chemistry  gistd:_Aspect_amount_of_substance  gistd:_UnitOfMeasure_millimole)
#     (gistd:_Discipline_chemistry  gistd:_Aspect_amount_of_substance  gistd:_UnitOfMeasure_mole)
#     (gistd:_Discipline_chemistry  gistd:_Aspect_molar_concentration  gistd:_UnitOfMeasure_international_unit_per_liter)

     (gistd:_Discipline_communications  gistd:_Aspect_data_rate  gistd:_UnitOfMeasure_gigabit_per_second)
     (gistd:_Discipline_communications  gistd:_Aspect_data_rate  gistd:_UnitOfMeasure_megabit_per_second)

     (gistd:_Discipline_computing  gistd:_Aspect_amount_of_data  gistd:_UnitOfMeasure_bit)
     (gistd:_Discipline_computing  gistd:_Aspect_amount_of_data  gistd:_UnitOfMeasure_byte)
     (gistd:_Discipline_computing  gistd:_Aspect_amount_of_data  gistd:_UnitOfMeasure_terabyte)
     (gistd:_Discipline_computing  gistd:_Aspect_data_rate  gistd:_UnitOfMeasure_megabit_per_second)
     (gistd:_Discipline_computing  gistd:_Aspect_data_rate  gistd:_UnitOfMeasure_gigabit_per_second)

     (gistd:_Discipline_earth_sciences  gistd:_Aspect_atmospheric_pressure  gistd:_UnitOfMeasure_millimeter_of_mercury)
     (gistd:_Discipline_earth_sciences  gistd:_Aspect_atmospheric_pressure  gistd:_UnitOfMeasure_psi)
     (gistd:_Discipline_earth_sciences  gistd:_Aspect_atmospheric_pressure  gistd:_UnitOfMeasure_standard_atmosphere)

     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_capacitance  gistd:_UnitOfMeasure_farad)
     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_electric_charge  gistd:_UnitOfMeasure_coulomb)
     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_electric_current  gistd:_UnitOfMeasure_ampere)
#     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_electric_current  gistd:_UnitOfMeasure_milliampere)
#     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_electric_power  gistd:_UnitOfMeasure_kilowatt)
#     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_electric_power  gistd:_UnitOfMeasure_megawatt)
     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_electric_power  gistd:_UnitOfMeasure_watt)
     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_electric_resistance  gistd:_UnitOfMeasure_ohm)
#     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_electrical_energy  gistd:_UnitOfMeasure_joule)
     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_electrical_energy  gistd:_UnitOfMeasure_kilowatt_hour)
#     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_electrical_energy  gistd:_UnitOfMeasure_watt_hour)
     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_impedance  gistd:_UnitOfMeasure_ohm)
     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_inductance  gistd:_UnitOfMeasure_henry)
     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_magnetic_flux  gistd:_UnitOfMeasure_maxwell)
     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_magnetic_flux_density  gistd:_UnitOfMeasure_gauss)
     (gistd:_Discipline_electricity_and_magnetism  gistd:_Aspect_magnetic_flux_density  gistd:_UnitOfMeasure_tesla)

     (gistd:_Discipline_finance  gistd:_Aspect_labor_consumption_rate  gistd:_UnitOfMeasure_day_per_week)
     (gistd:_Discipline_finance  gistd:_Aspect_labor_consumption_rate  gistd:_UnitOfMeasure_hour_per_week)
     (gistd:_Discipline_finance  gistd:_Aspect_monetary_value  gistd:_UnitOfMeasure_US_Dollar)
     (gistd:_Discipline_finance  gistd:_Aspect_monetary_value_per_duration  gistd:_UnitOfMeasure_US_Dollar_per_hour)

     (gistd:_Discipline_fluid_dynamics  gistd:_Aspect_force_per_area  gistd:_UnitOfMeasure_inch_of_mercury)
     (gistd:_Discipline_fluid_dynamics  gistd:_Aspect_force_per_area  gistd:_UnitOfMeasure_millimeter_of_mercury)
     (gistd:_Discipline_fluid_dynamics  gistd:_Aspect_force_per_area  gistd:_UnitOfMeasure_pascal)
     (gistd:_Discipline_fluid_dynamics  gistd:_Aspect_force_per_area  gistd:_UnitOfMeasure_pound_force_per_square_inch)
#     (gistd:_Discipline_fluid_dynamics  gistd:_Aspect_force_per_area  gistd:_UnitOfMeasure_psi)
     (gistd:_Discipline_fluid_dynamics  gistd:_Aspect_force_per_area  gistd:_UnitOfMeasure_standard_atmosphere)
#     (gistd:_Discipline_fluid_dynamics  gistd:_Aspect_volume_flow_rate  gistd:_UnitOfMeasure_liter_per_minute)
#     (gistd:_Discipline_fluid_dynamics  gistd:_Aspect_volume_flow_rate  gistd:_UnitOfMeasure_us_gallon_per_day)

     (gistd:_Discipline_mechanics  gistd:_Aspect_force  gistd:_UnitOfMeasure_dyne)
#     (gistd:_Discipline_mechanics  gistd:_Aspect_force  gistd:_UnitOfMeasure_gram_force)
     (gistd:_Discipline_mechanics  gistd:_Aspect_force  gistd:_UnitOfMeasure_kilogram_force)
     (gistd:_Discipline_mechanics  gistd:_Aspect_force  gistd:_UnitOfMeasure_newton)
     (gistd:_Discipline_mechanics  gistd:_Aspect_force  gistd:_UnitOfMeasure_pound_force)
     (gistd:_Discipline_mechanics  gistd:_Aspect_power  gistd:_UnitOfMeasure_horsepower)
#     (gistd:_Discipline_mechanics  gistd:_Aspect_power  gistd:_UnitOfMeasure_joule_per_hour)
     (gistd:_Discipline_mechanics  gistd:_Aspect_power  gistd:_UnitOfMeasure_joule_per_second)
#     (gistd:_Discipline_mechanics  gistd:_Aspect_ratio_of_distances  gistd:_UnitOfMeasure_grade)
     (gistd:_Discipline_mechanics  gistd:_Aspect_torque  gistd:_UnitOfMeasure_foot_pound_force)
#     (gistd:_Discipline_mechanics  gistd:_Aspect_torque  gistd:_UnitOfMeasure_kilogram_force_meter)
     (gistd:_Discipline_mechanics  gistd:_Aspect_torque  gistd:_UnitOfMeasure_newton_meter)
    
#     (gistd:_Discipline_mechanics  gistd:_Aspect_power  gistd:_UnitOfMeasure_btu_per_hour)
     (gistd:_Discipline_mechanics  gistd:_Aspect_power  gistd:_UnitOfMeasure_horsepower)
#     (gistd:_Discipline_mechanics  gistd:_Aspect_power  gistd:_UnitOfMeasure_joule_per_hour)
     (gistd:_Discipline_mechanics  gistd:_Aspect_power  gistd:_UnitOfMeasure_joule_per_second)
#     (gistd:_Discipline_mechanics  gistd:_Aspect_power  gistd:_UnitOfMeasure_kilowatt)
#     (gistd:_Discipline_mechanics  gistd:_Aspect_power  gistd:_UnitOfMeasure_megawatt)
#     (gistd:_Discipline_mechanics  gistd:_Aspect_power  gistd:_UnitOfMeasure_therm_us_per_hour)
     (gistd:_Discipline_mechanics  gistd:_Aspect_power  gistd:_UnitOfMeasure_watt)


     (gistd:_Discipline_medicine  gistd:_Aspect_absorbed_dose  gistd:_UnitOfMeasure_gray)
     (gistd:_Discipline_medicine  gistd:_Aspect_blood_pressure  gistd:_UnitOfMeasure_millimeter_of_mercury)
     (gistd:_Discipline_medicine  gistd:_Aspect_heart_rate  gistd:_UnitOfMeasure_count_per_minute)
     (gistd:_Discipline_medicine  gistd:_Aspect_rate_of_morbidity  gistd:_UnitOfMeasure_cases_per_1000_individuals_per_year)
     (gistd:_Discipline_medicine  gistd:_Aspect_rate_of_mortality  gistd:_UnitOfMeasure_deaths_per_million_individuals_per_year)
     (gistd:_Discipline_medicine  gistd:_Aspect_respiratory_rate  gistd:_UnitOfMeasure_count_per_minute)

     (gistd:_Discipline_numeric  gistd:_Aspect_number  gistd:_UnitOfMeasure_number)
     (gistd:_Discipline_numeric  gistd:_Aspect_number_of_things  gistd:_UnitOfMeasure_count)
     (gistd:_Discipline_numeric  gistd:_Aspect_number_of_things  gistd:_UnitOfMeasure_dozen)
     (gistd:_Discipline_numeric  gistd:_Aspect_number_of_things  gistd:_UnitOfMeasure_each)
     (gistd:_Discipline_numeric  gistd:_Aspect_number_of_things  gistd:_UnitOfMeasure_item)
     (gistd:_Discipline_numeric  gistd:_Aspect_number_of_things  gistd:_UnitOfMeasure_one)
     (gistd:_Discipline_numeric  gistd:_Aspect_number_of_things  gistd:_UnitOfMeasure_thing)
     (gistd:_Discipline_numeric  gistd:_Aspect_number_of_things  gistd:_UnitOfMeasure_unitless)
     (gistd:_Discipline_numeric  gistd:_Aspect_probability  gistd:_UnitOfMeasure_number)
     (gistd:_Discipline_numeric  gistd:_Aspect_probability  gistd:_UnitOfMeasure_percent)
     (gistd:_Discipline_numeric  gistd:_Aspect_ratio  gistd:_UnitOfMeasure_fraction)
     (gistd:_Discipline_numeric  gistd:_Aspect_ratio  gistd:_UnitOfMeasure_percent)
     (gistd:_Discipline_numeric  gistd:_Aspect_ratio_of_masses  gistd:_UnitOfMeasure_milligram_per_kilogram)
     (gistd:_Discipline_numeric  gistd:_Aspect_score  gistd:_UnitOfMeasure_number)
     (gistd:_Discipline_numeric  gistd:_Aspect_score  gistd:_UnitOfMeasure_percent)
#     (gistd:_Discipline_numeric  gistd:_Aspect_score  gistd:_UnitOfMeasure_star)

#     (gistd:_Discipline_optics  gistd:_Aspect_luminance  gistd:_UnitOfMeasure_foot_candle)
#     (gistd:_Discipline_optics  gistd:_Aspect_luminance  gistd:_UnitOfMeasure_lambert)
#     (gistd:_Discipline_optics  gistd:_Aspect_luminous_flux  gistd:_UnitOfMeasure_candela)
#     (gistd:_Discipline_optics  gistd:_Aspect_luminous_flux  gistd:_UnitOfMeasure_lumen)
#     (gistd:_Discipline_optics  gistd:_Aspect_luminous_intensity  gistd:_UnitOfMeasure_candela)
#     (gistd:_Discipline_optics  gistd:_Aspect_luminous_intensity  gistd:_UnitOfMeasure_lumen)
#     (gistd:_Discipline_optics  gistd:_Aspect_luminous_intensity_per_unit_of_power  gistd:_UnitOfMeasure_lumen_per_watt)

     (gistd:_Discipline_processes  gistd:_Aspect_cycle_time  gistd:_UnitOfMeasure_day)
     (gistd:_Discipline_processes  gistd:_Aspect_cycle_time  gistd:_UnitOfMeasure_week)
     (gistd:_Discipline_processes  gistd:_Aspect_unit_cost   gistd:_UnitOfMeasure_US_Dollar)
    
#    (gistd:_Discipline_propulsion  gistd:_Aspect_thrust  gistd:_UnitOfMeasure_newton)

    (gistd:_Discipline_radiology  gistd:_Aspect_absorbed_dose   gistd:_UnitOfMeasure_gray)
    (gistd:_Discipline_radiology  gistd:_Aspect_activity   gistd:_UnitOfMeasure_becquerel)
#    (gistd:_Discipline_radiology  gistd:_Aspect_activity   gistd:_UnitOfMeasure_megabecquerel)
#    (gistd:_Discipline_radiology  gistd:_Aspect_activity   gistd:_UnitOfMeasure_gigabecquerel)
    (gistd:_Discipline_radiology  gistd:_Aspect_dose_equivalent  gistd:_UnitOfMeasure_sievert)
    (gistd:_Discipline_radiology  gistd:_Aspect_magnetic_flux_density gistd:_UnitOfMeasure_tesla)
    (gistd:_Discipline_radiology  gistd:_Aspect_frequency             gistd:_UnitOfMeasure_hertz)

     (gistd:_Discipline_radiometry gistd:_Aspect_spectral_radiant_energy_density  gistd:_UnitOfMeasure_joule_per_quartic_meter)

#     (gistd:_Discipline_solid_state_physics gistd:_Aspect_electron_affinity  gistd:_UnitOfMeasure_electron_volt)
#     (gistd:_Discipline_solid_state_physics gistd:_Aspect_ionization_energy  gistd:_UnitOfMeasure_electron_volt)

     (gistd:_Discipline_space_and_time  gistd:_Aspect_altitude  gistd:_UnitOfMeasure_foot)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_altitude  gistd:_UnitOfMeasure_kilometer)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_altitude  gistd:_UnitOfMeasure_meter)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_altitude  gistd:_UnitOfMeasure_mile)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_angle  gistd:_UnitOfMeasure_degree)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_angle  gistd:_UnitOfMeasure_minute_angle)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_angle  gistd:_UnitOfMeasure_radian)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_angle  gistd:_UnitOfMeasure_revolution)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_angular_velocity  gistd:_UnitOfMeasure_degree_per_second)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_angular_velocity  gistd:_UnitOfMeasure_revolution_per_minute)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_area  gistd:_UnitOfMeasure_acre)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_area  gistd:_UnitOfMeasure_square_centimeter)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_area  gistd:_UnitOfMeasure_square_foot)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_area  gistd:_UnitOfMeasure_square_inch)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_area  gistd:_UnitOfMeasure_square_meter)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_distance  gistd:_UnitOfMeasure_centimeter)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_distance  gistd:_UnitOfMeasure_foot)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_distance  gistd:_UnitOfMeasure_inch)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_distance  gistd:_UnitOfMeasure_kilometer)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_distance  gistd:_UnitOfMeasure_meter)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_distance  gistd:_UnitOfMeasure_mile)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_distance  gistd:_UnitOfMeasure_us_survey_foot)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_distance  gistd:_UnitOfMeasure_yard)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_duration  gistd:_UnitOfMeasure_day)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_duration  gistd:_UnitOfMeasure_hour)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_duration  gistd:_UnitOfMeasure_millisecond)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_duration  gistd:_UnitOfMeasure_minute)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_duration  gistd:_UnitOfMeasure_second)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_duration  gistd:_UnitOfMeasure_week)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_duration  gistd:_UnitOfMeasure_year)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_frequency  gistd:_UnitOfMeasure_gigahertz)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_frequency  gistd:_UnitOfMeasure_hertz)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_number_per_duration  gistd:_UnitOfMeasure_number_per_hour)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_number_per_volume  gistd:_UnitOfMeasure_liter)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_percentage  gistd:_UnitOfMeasure_percent)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_speed  gistd:_UnitOfMeasure_foot_per_second)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_speed  gistd:_UnitOfMeasure_kilometer_per_hour)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_speed  gistd:_UnitOfMeasure_knot)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_speed  gistd:_UnitOfMeasure_meter_per_hour)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_speed  gistd:_UnitOfMeasure_mile_per_hour)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_volume  gistd:_UnitOfMeasure_cubic_foot)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_volume  gistd:_UnitOfMeasure_cubic_meter)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_volume  gistd:_UnitOfMeasure_cubic_yard)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_volume  gistd:_UnitOfMeasure_liter)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_volume  gistd:_UnitOfMeasure_tablespoon)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_volume  gistd:_UnitOfMeasure_teaspoon)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_volume  gistd:_UnitOfMeasure_us_gallon)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_volume  gistd:_UnitOfMeasure_us_liquid_cup)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_volume  gistd:_UnitOfMeasure_us_liquid_ounce)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_volume  gistd:_UnitOfMeasure_us_liquid_pint)
     (gistd:_Discipline_space_and_time  gistd:_Aspect_volume  gistd:_UnitOfMeasure_us_liquid_quart)

     (gistd:_Discipline_thermodynamics  gistd:_Aspect_amount_of_heat  gistd:_UnitOfMeasure_british_thermal_unit_international)
     (gistd:_Discipline_thermodynamics  gistd:_Aspect_amount_of_heat  gistd:_UnitOfMeasure_erg)
     (gistd:_Discipline_thermodynamics  gistd:_Aspect_amount_of_heat  gistd:_UnitOfMeasure_international_calorie)
     (gistd:_Discipline_thermodynamics  gistd:_Aspect_amount_of_heat  gistd:_UnitOfMeasure_joule)
     (gistd:_Discipline_thermodynamics  gistd:_Aspect_amount_of_heat  gistd:_UnitOfMeasure_therm_us)
     (gistd:_Discipline_thermodynamics  gistd:_Aspect_energy  gistd:_UnitOfMeasure_joule)
     (gistd:_Discipline_thermodynamics  gistd:_Aspect_temperature  gistd:_UnitOfMeasure_degree_celsius)
     (gistd:_Discipline_thermodynamics  gistd:_Aspect_temperature  gistd:_UnitOfMeasure_degree_fahrenheit)
     (gistd:_Discipline_thermodynamics  gistd:_Aspect_temperature  gistd:_UnitOfMeasure_kelvin)
     }
  
  
  ?unit gist:isMemberOf  ?unitGroup .  
  ?aspect gist:hasUnitGroup ?unitGroup  .  
  optional {?aspect gist:isCategorizedBy ?discipline .
            ?discipline ?disciplinePredicate ?disciplineObject .}
  
  ?unit      ?unitPredicate      ?unitObject .  
  ?unitGroup ?unitGroupPredicate ?unitGroupObject .  
  ?aspect    ?aspectPredicate    ?aspectObject .

  filter(?unitPredicate   != gist:isMemberOf)
  filter(?aspectPredicate != gist:hasUnitGroup)
  filter(?aspectPredicate != gist:isCategorizedBy)
}
