# query to get units of measure reference data for a specific client
# modify the input data as needed for the client

construct {
  ?unitOfMeasure gist:isMemberOf   ?unitGroup .
  ?aspect        gist:hasUnitGroup ?unitGroup .
  ?aspect        gist:isCategorizedBy ?discipline . 
  ?discipline    ?disciplinePredicate    ?disciplineObject .
  ?aspect        ?aspectPredicate        ?aspectObject .
  ?unitGroup     ?unitGroupPredicate     ?unitGroupObject .
  ?unitOfMeasure ?unitOfMeasurePredicate ?unitOfMeasureObject .  
  }

where {

# input is a list of Aspects, a list of Unit Groups, and a list of Units the client will be using

# units to include
values ?unitOfMeasure {
gistd:_UnitOfMeasure_kilogram
gistd:_UnitOfMeasure_ounce_mass
gistd:_UnitOfMeasure_pound
}
  
# unit groups to include
values ?unitGroup {
gistd:_UnitGroup_mass 
}
  
# aspects to include
values ?aspect {
gistd:_Aspect_mass
}
   
 ?unitOfMeasure gist:isMemberOf   ?unitGroup .
 ?aspect        gist:hasUnitGroup ?unitGroup .

 optional {?aspect gist:isCategorizedBy ?discipline}
  
# get details of each aspect, unit group, unit, and discipline

{?aspect        ?aspectPredicate        ?aspectObject .
 filter(?aspectPredicate != gist:hasUnitGroup)
 filter(?aspectPredicate != gist:isCategorizedBy)
 }
  
union {?unitGroup     ?unitGroupPredicate     ?unitGroupObject .}
  
union {?unitOfMeasure ?unitOfMeasurePredicate ?unitOfMeasureObject .
        filter(?unitOfMeasurePredicate != gist:isMemberOf)
        }

union {?discipline     ?disciplinePredicate     ?disciplineObject .}
}
